### ISSUE TITLE
Updating progress

### ISSUE THREAD

**Issue by Abdelaziz-Ali** [Alejandroq12/bookstore#6]
Hello, Julio
I was checking your project I noticed two bugs, and I have one recommendation, I hope it helps in your project.

1- The two bugs are when the user updates the progress with no values for (page number or progress rate) it displays Nan.

![page-progress](https://github.com/Alejandroq12/bookstore/assets/107482707/ad6cf0a8-42ba-4ad2-a5cd-2b319f516d5f)

2- My recommendation is to change the placeholder's Text (Enter updated chapter to Enter updated page).

![page-number](https://github.com/Alejandroq12/bookstore/assets/107482707/3cf9329d-00af-490b-bec7-40e32056d8f9)

I like your progress in that project it looks organized and professional,
Keep it up.

**Comment by Alejandroq12** [comment]
@Abdelaziz-Ali Thank you very much! This feedback was great. I solved it.
Have a good day.
